### ISSUE TITLE
jd_zy_ddwj_Mod.js  只做几个任务，很多任务都不做了

### ISSUE THREAD

**Issue by linyali888** [ccwav/QLScript#19]
TypeError: Cannot read property 'status' of undefined
    at /ql/scripts/zy_ddwj.js:374:43
    at got.post.then.message (/ql/scripts/zy_ddwj.js:972:6)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

会这样

**Comment by ccwav** [comment]
个例，不处理
